### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by Amirk390** [FACN3/Teleport#47]
Good job on the web guys it looks good :)

i think you should try making the image responsive tho? 

(when the screen is smaller maybe the image should get smaller as well?)

**Comment by hasansaad1** [comment]
@Amirk390 check pull request #70

**Comment by Amirk390** [comment]
![](http://d2trtkcohkrm90.cloudfront.net/images/emoji/apple/ios-10/256/clapping-hands.png)
